# Generated by Django 5.1.7 on 2025-06-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_of_the_month', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='fc25.png', upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('first_price', models.IntegerField(blank=True, default=0, null=True)),
                ('second_price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('genre', models.ManyToManyField(to='game_of_the_month.genre')),
            ],
        ),
        migrations.CreateModel(
            name='UpComingGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='fc25.png', upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('genre', models.ManyToManyField(to='game_of_the_month.genre')),
            ],
        ),
    ]
