# Generated by Django 5.1.7 on 2025-06-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_of_the_month', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.ImageField(default='fc25.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
