# Generated by Django 5.1.7 on 2025-06-17 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_of_the_month', '0002_genre_image_genre_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='slug',
        ),
    ]
