# Generated by Django 5.1.7 on 2025-06-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_of_the_month', '0003_remove_genre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(blank=True, default='fc25.png', null=True, upload_to=''),
        ),
    ]
